language: python
install:
  - pip install tox
  - pip install -r requirements-test.txt
script:
  - tox
env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py27-django110
  - TOXENV=py34-django110
